name: Build and Package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: msbuild /t:build /p:Configuration=Release
    - name: Package
      run: 7z a MyApp.zip bin/Release/*
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp
        path: MyApp.zip
